CONTRIBUTING.md

Adição do arquivo CONTRIBUTING.md para auxiliar os novos contribuidores

Adição do contributing.md

---

docs/contributing/code-of-conduct.md

Tradução referente ao arquivo code-of-conduct.md.

Traducao code of conduct

---

docs/contributing/code-of-conduct.md

**MOTIVAÇÃO**
Pequenas correções ortográficas, acrescentar itálicos nos termos em lingua estrangeira e melhoramentos de estilo

melhoramentos no traducao d codigo de conduta

---

docs/docs/gatsby-cli.md

[WIP] tradução do arquivo docs/docs/gatsby-cli.md 

---

README.md

pequenas correções de texto

---

docs/tutorial/index.md

gatsby-pt-BR/docs/tutorial/index.md 
Verifiquem a tradução que fiz de Source Plugin. Quero ver se é a melhor maneira no contexto, procurei no sheet do Google com os termos porém não se adequou ali.

Translate docs/tutorial/index.md to pt-br

---

docs/contributing/how-to-contribute.md

[contributing/how-to-contribute](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/how-to-contribute.md)

translation how-to-contribute

---

docs/contributing/blog-and-website-contributions.md

gatsby-pt-BR/docs/contributing/blog-and-website-contributions.md

Translate blog and website contributions to PT-BR

---

docs/contributing/contributor-swag.md

[contributing/contributor-swag.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/contributor-swag.md)
A tradução de "swag" é um pouco duvidosa, e provavelmente não fui consistente tentando deixar o mais claro possível o que isso realmente significa. Aberto a sugestões (pedi no Discord também).

Added contributor-swag translation

---

docs/contributing/code-contributions.md

Arquivo [code-contributions.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/code-contributions.md).

Adição da tradução do arquivo code-contributions

---

docs/contributing/how-to-file-an-issue.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/how-to-file-an-issue.md
Tive dificuldade em alguns pontos para diferenciar o significado da palavra issue, se ela estava se referindo a uma issue propriamente dita ou a um problema, então é um ponto a se analizar no PR.

Translation of the how-to-file-an-issue section

---

docs/tutorial/part-zero/index.md

https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-zero
A tradução original seguiu a versão inglesa bem fielmente porém essa estratégia comprometeu um pouco a fluidez da leitura.
Procurei fazer melhoramentos de estilo na tentativa de deixar a leitura mais natural e fluída em Português.
Revisei somente até a parte de fala da CLI, pretendo revisar mais desse conteúdo em PRs futuras.

Tutorial parte zero: revisão

---

docs/contributing/pair-programming.md

docs/contributing/pair-programming.md

Add translate to pair programming

---

docs/contributing/how-to-open-a-pull-request.md

gatsby-pt-BR/docs/contributing/how-to-open-a-pull-request.md
Os `Recursos adicionais` serão mantidos os mesmos?

Translate docs/contributing/how-to-open-a-pull-request.md to pt-br

---

docs/docs/glossary.md

[docs/glossary.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/glossary.md)
Tem vários termos que fiquei na dúvida se deveria traduzir. Por isso muito provavelmente será necessário fazer ajustes.
Ainda tem termos faltando traduzir, acredito que o @jay-jlm irá revisar e finalizar.

Translate of glossary

---

CODEOWNERS
CONTRIBUTING.md
README.md

Atualizar informações do repositório

Atualizações para o Repositório [URGENTE]

---

docs/contributing/submit-to-starter-library.md

[contributing/submit-to-starter-library](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/submit-to-starter-library.md)

translation [contributing/submit-to-starter-library]

---

GLOSSARY.md
style-guide.md

* Adicionado o arquivo `GLOSSARY.md`, contendo as traduções comuns.
* Os termos comuns da [tradução do React](https://github.com/reactjs/pt-BR.reactjs.org/blob/master/GLOSSARY.md) foram inseridos como base.
* Adicionados os termos do [Google Sheet](https://docs.google.com/spreadsheets/d/1TLztI-jrPslCt0fgk4B9tGnhhS_7JQZJfMql1ePsIZo/edit#gid=0) original.
* Modificado o arquivo `style-guide.md` para conter um link para o novo arquivo.
Adicionar um arquivo dedicado ajuda a localização de termos e à manter sob controle de versão no Github. Todas as modificações serão auditadas por meio de PRs.

Adding a Glossary file and poiting style guide to it

---

docs/contributing/how-to-run-a-gatsby-workshop.md

docs/contributing/how-to-run-a-gatsby-workshop.md
[Link do arquivo em minha branch/repo](https://github.com/thiagorowof/gatsby-pt-BR/commit/142305812c09aa52a6bbbe7f9e0ce2f49693512b#diff-99ae7586a0cea6073e4d0aa72cb61a58)

Tradução da página how to run a gatsby workshop

---

docs/contributing/how-to-label-an-issue.md

Em alguns momentos senti a necessidade de chamar a palavra label de classificador por fazer mais sentido ao contexto da frase, não encontrei um sentido melhor na hora da tradução.

translate how-to-label-an-issue

---

docs/contributing/docs-contributions.md

docs/contributing/docs-contributions.md
Algumas vezes a palavra `docs` pode ter diferença de sentido como: documentos, documentação, documentações, documento. Então uma revisão a mais nesses casos é bem vinda para garantir que o sentido original tenha sido mantido.

Traducao docs contributions

---

docs/contributing/how-to-open-a-pull-request.md

Arquivo referente a issue #29, how-o-open-a-pull-request.md

Adiciona correções

---

docs/tutorial/part-five/index.md

tutorial/part-five/index.md
[link](https://github.com/gatsbyjs/gatsby/blob/master/docs/tutorial/part-five/index.md)
Palavras que eu não traduzi:
* query/queries
* autocomplete
* dropdown

Tradução do tutorial/part-five

---

docs/contributing/setting-up-your-local-dev-environment.md

[docs/contributing/setting-up-your-local-dev-environment.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/setting-up-your-local-dev-environment.md)
Enviei um PR na documentação oficial do Gatsby com esta mudança e ela já foi aceita: https://github.com/gatsbyjs/gatsby/pull/19303
Portanto, eu já refleti esta mudança aqui na tradução.
Eu traduzi `Create a topic branch` para `Crie um branch com um nome bem descritivo`. Conferi que o prefixo `topics/` não é um padrão do Gatsby, apenas um exemplo pontual. Acredito ter mantido o significado e ter conseguido passar a intenção da documentação original, o que seria mais difícil de atingir se ficasse tentando encaixar a palavra "tópico" de alguma forma.
Adicionei 5 novas palavras ao glossário, mantendo todas no original em …

Tradução da página setting-up-your-local-dev-environment.

---

docs/contributing/submit-to-plugin-library.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/submit-to-plugin-library.md

tradução da página submit-to-plugin-library

---

docs/docs/quick-start.md

`docs/docs/quick-start.md`. Link para o [arquivo original](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/quick-start.md).
Acredito que seja importante atualizarmos o glossário com algumas expressões a mais, como "bundle" e "build", por exemplo.
É interessante que usemos a mesma nomenclatura quando traduzirmos essas expressões técnicas que não possuem uma palavra específica em português.

Adding translations for Quick Start

---

docs/tutorial/part-four/index.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/tutorial/part-four/index.md

Tradução da quarta parte do tutorial

---

docs/contributing/how-to-make-a-reproducible-test-case.md

Relates to: #9 
`docs/contributing/how-to-make-a-reproducible-test-case`
original: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

Translate how-to-make-a-reproducible-test-case

---

docs/contributing/submit-to-creator-showcase.md

submit-to-creator-showcase.md
[link](https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/submit-to-creator-showcase.md)
Palavras que eu não traduzi:
* PR
* Merge
* Template

Tradução do submit-to-creator-showcase

---

docs/contributing/community.md

[contributing/community.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/community.md)
Dúvida na tradução de "free swag" e na tradução de um dos valores: "you belong here"

Add community translation

---

docs/tutorial/part-seven/index.md

Tradução tutorial/part-seven 

---

docs/contributing/managing-pull-requests.md

docs/contributing/managing-pull-requests

Traducao managing pull requests

---

docs/contributing/organize-a-gatsby-event.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/organize-a-gatsby-event.md
Não traduzi "$300", quero opiniões quanto ao termo "lanche e estudos".

Tradução do organize a gatsby event

---

docs/docs/styled-components.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/styled-components.md

translate styled-components /docs

---

docs/tutorial/part-six/index.md

https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-six

[TRADUÇÃO] Tutorial - Parte 6

---

docs/docs/using-gatsby-professionally.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/using-gatsby-professionally.md
Tem 2 termos que fiquei em dúvida sobre como traduzir e não encontrei no glossário:
* stakeholders (4º parágrafo): traduzi como "partes interessadas"
* marketers (4º parágrafo): traduzi como "comerciantes" (achei estranho, mas não identifiquei uma tradução melhor).

traducao-using-gatsby-professionally.md

---

docs/docs/testing.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/testing.md

translate testing.md

---

docs/docs/babel.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/babel.md
Fiquei em dúvida para tradução de "browser share". Coloquei "participação do navegador" mas se tiverem outras sugestões podem sugerir.

translate babel.md

---

docs/docs/add-page-metadata.md

[add-page-metadata.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/add-page-metadata.md)

Tradução para add-page-metadata.md

---

docs/docs/best-practices-for-orgs.md

[/docs/docs/best-practices-for-orgs.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/best-practices-for-orgs.md)

translate: best-practices-for-orgs.md

---

docs/docs/recipes.md

[gatsby-pt-BR/docs/recipes.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/recipes.md)

[WIP] translate: recipes.md

---

docs/contributing/how-to-write-a-stub.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/how-to-write-a-stub.md
Senti um pouco confusa a parte de "Converting a Stub to a Doc", se puderem dar uma atenção nesse pedaço. Melhorias são bem vindas.

translate: how-to-write-a-stub.md

---

docs/contributing/site-showcase-submissions.md

docs/contributing/site-showcase-submissions.md
Fiquei em dúvida se deveria traduzir o nome das tags de categorias/conteúdos, caso seja necessário envio em outro commit. :)

translate: site-showcase-submission.md

---

docs/docs/api-files.md

[docs/docs/api-files.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/api-files.md)

Translate api-files.md

---

docs/docs/naming-a-plugin.md

[`docs/naming-a-plugin.md`](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/naming-a-plugin.md)

translate: naming-a-plugin.md 

---

docs/tutorial/part-three/index.md

docs/tutorial/part-three/index.md

translate:  tutorial/part-three/index.md

---

docs/docs/building-a-portfolio.md

[docs/docs/building-a-portfolio.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/building-a-portfolio.md)

translate: building-a-portfolio.md

---

docs/docs/api-files-gatsby-node.md

[api-files-gatsby-node.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/api-files-gatsby-node.md)

translate: api-files-gatsby-node.md

---

docs/docs/content-and-data.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/content-and-data.md

translate: content-and-data.md

---

docs/docs/adding-page-transitions.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/adding-page-transitions.md

translate: adding-page-transitions.md

---

docs/docs/headless-cms.md

[headless-cms.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/headless-cms.md)
Optei por não traduzir os termos "frontend" e "headless CMS", caso alguém tenha alguma sugestão será muito bem vinda :).
O termo "source plugins" foi traduzido como "plugins fornecedores de dados" se alguém tiver alguma sugestão melhor pro contexto seria ótimo.

Traducao headless cms

---

docs/docs/css-modules.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/css-modules.md

translate: css-modules.md

---

docs/docs/convincing-others.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/convincing-others.md
Fiquei em dúvida em um trecho que tem o seguinte:
```
[...] and helping convince them to use it (or to let you use it) [...]
```
Não sei ao certo se a traduação ficou perfeita. Seria interessante ter uma segunda opinião para ver se o texto faz sentido em português.

traducao-convincing-others.md

---

docs/docs/gatsby-core-philosophy.md

[gatsby-core-philosophy](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/gatsby-core-philosophy.md)

Traducao gatsby core philosophy

---

docs/docs/conceptual-guide.md

Adds conceptual guide translation

---

docs/docs/glamor.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/glamor.md

Adds Glamor translate

---

docs/docs/localization-i18n.md

localization-i18n.md
https://github.com/renatamarques97/gatsby-pt-BR/blob/translation/localization-i18n.md/docs/docs/localization-i18n.md

translation of localization-i18n.md

---

docs/docs/bulma.md

bulma.md
https://github.com/renatamarques97/gatsby-pt-BR/blob/translation/bulma.md/docs/docs/bulma.md

translation of bulma.md

---

docs/docs/guides.md

<a href="https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/guides.md">guides.md</a>
não

traducao-guides.md

---

docs/docs/linking-between-pages.md

docs/docs/linking-between-pages.md

Adds linking between pages translation

---

docs/docs/deploying-and-hosting.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/deploying-and-hosting.md

Adds deploying hosting translation

---

docs/docs/creating-a-transformer-plugin.md

traducao creating-a-transformer-plugin

---

docs/docs/graphql-concepts.md

[graphql-concepts.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/graphql-concepts.md)

Traduzido graphql-concepts.md

---

docs/docs/first-professional-project.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/first-professional-project.md
Fiquei em dúvida em 3 casos:
* Se mantinha "bottom-up" e "top-down" ao invés de traduzi-los. Decidi manter o original em inglês.
* Se traduzia ou não _landing pages_. Decidi manter em inglês.
* Como traduzir _brochure sites_. Traduzi como "sites de propaganda".

Tradução first-professional-project.md

---

docs/docs/porting-to-gatsby.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/porting-to-gatsby.md

Add porting to gatsby

---

docs/docs/eslint.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/eslint.md

Adds ESlint translation

---

docs/docs/faster-recruiting.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/faster-recruiting.md

Adds faster recruiting translation

---

docs/docs/plugins.md

[plugins.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/plugins.md)

Add plugins.md traduction

---

docs/docs/routing.md

[routing.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/routing.md)
Se puderem analisar a utilização da palavras link/links/linking, ao meu ver deixei elas traduzidas ou não de acordo com o contexto da frase e para deixar mais de acordo com o comum. 
Optei por não traduzir prefetching por ser um termo ao meu ver do cotidiano e muito usado como fetch ou prefetch. A tradução com busca ou pré-busca poderia ficar confusa no contexto. Pensei em colocar pré-carregamento que é o que acontece na rota, ela "pré-carrega" a página que você vai acessar.

Tradução de routing.md

---

docs/docs/winning-over-stakeholders.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/winning-over-stakeholders.md
Traduzi:
* Winning over -> Convencendo
* Stakeholders -> interessados
* marketers -> profissionais de marketing
* **Não traduzi freelancer**

Tradução winning-over-stakeholders.md

---

docs/docs/adding-analytics.md

[adding-analytics.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/adding-analytics.md)
Nope

translating adding-analytics.md

---

docs/docs/cheat-sheet.md

translation of cheat-sheet.md

---

docs/docs/overview.md

<a href="https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/overview.md">overview.md</a>
O link apresentado neste arquivo esta levando a uma pagina de erro 404

traducao-overview.md

---

docs/docs/starters.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/starters.md

docs: Translate starters to pt-BR

---

docs/docs/coming-from-react-to-gatsby.md

`coming-from-react-to-gatsby.md`

translate: coming-from-react-to-gatsby.md

---

docs/tutorial/part-two/index.md

feature: translate tutorial part two.

---

docs/docs/add-a-manifest-file.md

<a href="https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/add-a-manifest-file.md">docs/docs/add-a-manifest-file.md</a>

Adiciona tradução para add-a-manifest-file.md

---

docs/docs/static-folder.md

static-folder.md
Dúvida na tradução dos seguintes termos:
- asset(s)
- workaround

Translate static-folder

---

docs/docs/mdx/getting-started.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/mdx/getting-started.md

docs: Translate MDX getting start file getting-started.md

---

docs/docs/css-in-js.md

[css-in-js](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/css-in-js.md)

Traducao css in js

---

docs/contributing/community-contributions.md

[community-contributions](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/community-contributions.md)
Inseguro se a 1º frase ficou com uma tradução bacana. (Linha 5)
>"A big part of what makes Gatsby great is each and every one of you in the community."
>"Grande parte do que torna o Gatsby excelente é cada um de vocês da comunidade."
O que acham melhor na 2º frase? (Linha 6)
> "Your contributions enrich the Gatsby experience and make it better every day."
> "Suas contribuições enriquecem a experiência do Gatsby e o torna melhor a cada dia", referenciando ao "Gatsby"
>"Suas contribuições enriquecem a experiência do Gatsby, **tornando-a** melhor a cada dia", fazendo referência a "experiência"
> "Suas contribuições enriquecem a experiência do Gatsby, **tornando-o** …

Translation of community-contributions to pt-br

---

docs/docs/security-in-gatsby.md

* [ x] Adição de uma nova tradução
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/security-in-gatsby.md
>
https://github.com/thiagorowof/gatsby-pt-BR/blob/traducao-security-in-gatsby/docs/docs/security-in-gatsby.md

security in gatsby translate

---

docs/docs/what-is-a-plugin.md

* [x ] Adição de uma nova tradução
what-is-a-plugin.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/what-is-a-plugin.md

Translate what-is-a-plugin to pt-br

---

docs/docs/gatsby-on-windows.md

* [ x ] Adição de uma nova tradução
https://github.com/renatamarques97/gatsby-pt-BR/blob/gatsby-on-windows/docs/docs/gatsby-on-windows.md

translation of gatsby-on-windows

---

docs/docs/sourcing-from-ghost.md

[sourcing-from-ghost.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/sourcing-from-ghost.md)
Sim, tive algumas dúvidas com relação a conceitos como Headless CMS e sobre o próprio título do documento em questão.

Translation of sourcing-from-ghost.md

---

docs/docs/adding-comments.md

adding-comments.md
fiquei em dúvida na tradução de post's slug, coloquei em itálico

translation of adding-comments.md

---

docs/docs/seo.md

[seo.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/seo.md)
Algumas palavras como "crawlers" e "default", deixei em inglês, pois não achei uma tradução legal, caso precisar alterar só avisar.

docs: added seo.md file translation

---

docs/docs/working-with-images.md

working-with-images.md 
https://github.com/CarlosEduLima/gatsby-pt-BR/blob/master/docs/docs/working-with-images.md
Não

Translate working-with-images.md to pt-br

---

docs/docs/making-components-discoverable.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/making-components-discoverable.md

Translating making-components-discoverable

---

docs/docs/testing-css-in-js.md

[testing-css-in-js.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/testing-css-in-js.md)

Translated testing-css-in-js.md

---

docs/docs/working-with-gifs.md

Não sei se deveria mas traduzi o alt da imagem do Markdown

Translate working-with-gifs

---

docs/docs/winning-over-executives.md

[winning-over-executives.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/winning-over-executives.md)
- Não consegui traduzir o último item na seção Estudos de Caso

Translate winning-over-executives.md

---

docs/docs/debugging.md

debugging.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/debugging.md

traducao-debugging.md

---

docs/docs/how-gatsby-boosts-career.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/how-gatsby-boosts-career.md
É feito uma referencia para alguns "docs", como o, **other developers**, **engineering leaders**, **marketers**, **executives** e **clients** nesse documento.
Durante a tradução reparei que a referencia**(link)** que é feita para o **clients** é o mesmo link do **executives**, ambos direcionam para **(/docs/winning-over-executives)**, acredito que seja um erro, então, coloquei o link que acredito ser correto para o  **clients**, que no caso, seria **(/docs/winning-over-clients)**. Peço, por gentileza, a confirmação para tal. 
Obrigado, galera!

translating how-gatsby-boosts-career.md

---

docs/docs/deploying-to-render.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/deploying-to-render.md

Translation of deploying-to-render.md

---

docs/docs/telemetry.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/telemetry.md
Não

Tradução do arquivo telemetry.md

---

docs/docs/preparing-your-environment.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/preparing-your-environment.md

translate: preparing-your-environment.md

---

docs/docs/sourcing-from-drupal.md

Tradução de sourcing-from-drupal.md

---

docs/docs/post-css.md

[post-css.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/post-css.md)

Tradução post-css

---

docs/docs/deploying-to-netlify.md

[deploying-to-netlify.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/deploying-to-netlify.md)
Na linha 27, fiquei na dúvida entra manter os nomes das pastas ou traduzir.

Translation of deploying-to-netlify.md

---

docs/docs/api-reference.md

[api-reference.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/api-reference.md)
Optei por não traduzir API

traducao-api-reference.md

---

docs/docs/releases-and-migration.md

[releases-and-migration.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/releases-and-migration.md)
Optei por traduzir release como versão e não lançamento pois acho que faz mais sentido para o desenvolvedor. Além disso, optei por traduzir major como principal.

traducao-releases-and-migration.md

---

docs/docs/tailwind-css.md

Closes #171
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/tailwind-css.md
Essa PR tem como objetivo adicionar a **Option #3: SCSS** no arquivo `tailwind-css.md`, conforme explico na [Issue #171](https://github.com/gatsbyjs/gatsby-pt-BR/issues/171).

adding option #3 on tailwind-css.md

---

docs/docs/using-gatsby-image.md

using-gatsby-image.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/using-gatsby-image.md

translation doc using-gatsby-image.md

---

docs/docs/winning-over-clients.md

[winning-over-clients.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/winning-over-clients.md)
_Gatsby Style Guide_: Guias de estilos Gatsby ou Guia de estilos do Gatsby, não sei qual o correto, mas mantive a primeira opção.

Translation of winning-over-clients.md

---

docs/docs/thinking-in-gatsby.md

[thinking-in-gatsby.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/thinking-in-gatsby.md)

traducao-thinking-in-gatsby.md

---

docs/docs/schema-customization.md

[schema-customization.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/schema-customization.md)
Não traduzi os termos: schema, resolver, action, node, markdown, playground.
Achei que fica melhor sem traduzir esses termos, pois se referem a objetos ou propriedades específicas do Gatsby ou do GraphQL. Como já foi sugerido pelo @iaurg  em #96

Traduzido schema-customization.md

---

docs/contributing/where-to-participate.md

[Where to Participate](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/where-to-participate.md)
Desculpa a demora, tive uns problemas de saúde mas já estou de volta.

Tradução where-to-participate

---

docs/docs/unit-testing.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/unit-testing.md
Duvida: traducao de Snapshot nao entendi bem o contexto , e mocking no contexto que foi utilizado.

translation of unit-testing.md

---

docs/docs/static-query.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/static-query.md
>
https://github.com/thiagorowof/gatsby-pt-BR/blob/traducao-static-query/docs/docs/static-query.md

static query translate

---

docs/docs/debugging-cache-issues.md

Debugging-cache-issues first translation to PT-BR

---

docs/docs/sharing-components-across-websites.md

[sharing-components-across-websites.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/sharing-components-across-websites.md)
Não

translation of sharing-components-across-websites.md

---

docs/docs/sourcing-from-prose.md

[sourcing-from-prose.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/sourcing-from-prose.md)
Tive dúvidas na tradução do termo "sourcing from". Olhei no glossário e no linguee mas não achei nenhuma opção que me agradasse. Somente após o primeiro commit tive a sacada de pesquisar por outros arquivos sourcing-from.xxxx já traduzidos. Foi aí que achei o [sourcing-from-ghost.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/sourcing-from-ghost.md) e gostei do termo "integrando". Por isso, já fiz um segundo commit fazendo essa alteração no title.

Traducao sourcing from prose

---

docs/docs/interactive-pages.md

[interactive-pages.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/interactive-pages.md)
Nenhum.

traducao: interactive-pages.md

---

docs/docs/building-a-blog.md

[building-a-blog.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/building-a-blog.md)
Nenhum.

traducao: building-a-blog.md

---

docs/docs/webpack-and-ssr.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/webpack-and-ssr.md
Eu achei que 'salvar' ficou melhor que 'escrever'.

Translate file webpack and ssr

---

docs/contributing/how-to-pitch-gatsby.md

`docs/contributing/how-to-pitch-gatsby.md`
Algumas expressões foram bem difíceis de traduzir. Por exemplo:
```
Think rocket ship vs. Winnebago. 
```
Ninguém no Brasil faz ideia do que é um Winnebago (marca de trailers, motorhome).
Então tentei fazer algumas aproximações que fizessem mais sentido com a nossa realidade.
Sugestões para esses casos são mais que bem vindas!

traducao how-to-pitch-gatsby

---

docs/docs/deploying-to-heroku.md

`/docs/docs/deploying-to-heroku.md`

Traducao deploying-to-heroku

---

docs/docs/themes/theme-composition.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/themes/theme-composition.md
Só fiquei um pouco receoso com relação ao trecho que menciona contexto React. Como não sou tão familiarizado com a biblioteca, fiquei na dúvida se deixei da forma mais apropriada.

First PT-BR translated version

---

docs/docs/basic-hardware-software-requirements.md

[basic-hardware-software-requirements.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/basic-hardware-software-requirements.md)
Percebi que a tradução de _requirements_ não estava legal e fiz um segundo commit.

traducao: basic-hardware-software-requirements.md

---

docs/docs/how-gatsby-works-with-github-pages.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/how-gatsby-works-with-github-pages.md

New translation: how-gatsby-works-with-github-pages.md

---

docs/docs/node-interface.md

[node-interface.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/node-interface.md)
Fiquei na duvida sobre se traduzia `node` para nó, acabei deixando `node` mesmo.

New translation: node-interface.md

---

docs/docs/themes/getting-started.md

[getting-started.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/themes/getting-started.md)

New translation:  themes/getting-started.md

---

docs/docs/debugging-html-builds.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/debugging-html-builds.md

New translation: debugging-html-builds.md

---

docs/docs/images-and-files.md

images-and-files.md
Nos trechos: "para evitar inchaço da imagem" e "prender sobre prós e contras de cada método" não sei se essa seria a melhor tradução.

New translation: images-and-files.md

---

docs/tutorial/part-eight/index.md
docs/tutorial/part-one/index.md
docs/tutorial/part-zero/index.md

[tutorial/part-zero/index.md](https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-zero)
[tutorial/part-one/index.md](https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-one)
[tutorial/part-eight/index.md](https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-eight)
O [tutorial/part-eight/index.md](https://github.com/gatsbyjs/gatsby-pt-BR/tree/master/docs/tutorial/part-eight) aparentemente não teve nenhuma mudança no sync.

Fix translation: sync docs/tutorial/*

---

CODEOWNERS

Atualizando lista de codeowners

Atualizando lista de codeowners

---

docs/docs/gatsby-on-linux.md

Tradução do arquivo [gatsby-on-linux.md](https://github.com/felipefbs/gatsby-pt-BR/blob/traducao-gatsby-on-linux.md/docs/docs/gatsby-on-linux.md)

Fix translation: gatsby-on-linux.md

---

docs/docs/v2-release-notes.md

https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/v2-release-notes.md

New translation: v2-release-notes.md

---

docs/docs/recipes.md
docs/docs/winning-over-clients.md

terminando a traducao completa do arquivo
[winning-over-clients.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/winning-over-clients.md)
[recipes.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/recipes.md)
O primeiro arquivo nao estava completamente traduzido, apenas finalizei. O segundo arquivo foi traduzido por completo.

Fix translation: winning-over-clients.md and recipes.md

---

docs/docs/gatsby-cli.md

[gatsby-cli](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/gatsby-cli.md)
Apenas finalizei a tradução e corrigi as tabelas que estavam erradas.

Fix translation: gatsby-cli.md

---

CONTRIBUTING.md

Fiz algumas alterações mínimas no arquivo [CONTRIBUTING.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/CONTRIBUTING.md) eliminando espaços extras e corrigindo erros ortográficos.

Fix: CONTRIBUTING.md typo

---

docs/contributing/organize-a-gatsby-event.md

[organize-a-gatsby-event.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/organize-a-gatsby-event.md)

Fix translation: organize-a-gatsby-event.md

---

docs/docs/glossary.md

[glossary.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/glossary.md)

Fix translation: glossary.md

---

docs/docs/what-is-a-plugin.md
docs/docs/what-you-dont-need-plugins-for.md

- [what-is-a-plugin.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/what-is-a-plugin.md)
- [what-you-dont-need-plugins-for.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/what-you-dont-need-plugins-for.md)

Fix translation: what-is-a-plugin.dm and what-you-dont-need-plugins-for.md

---

docs/docs/building-an-e-commerce-site.md

[building-an-e-commerce-site.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/building-an-e-commerce-site.md)
Não.

Fix translation: building-an-e-commerce-site.md

---

docs/contributing/code-contributions.md

[code-contributions.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/code-contributions.md)

Fix translation: contributing/code-contributions.md

---

docs/docs/porting-to-gatsby.md

[docs/porting-to-gatsby.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/porting-to-gatsby.md)

Fix translation: porting-to-gatsby.md

---

docs/docs/making-your-site-accessible.md

[making-your-site-accessible.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/making-your-site-accessible.md)
None yet

Fix translation: making-your-site-accessible.md

---

docs/contributing/setting-up-your-local-dev-environment.md

[setting-up-your-local-dev-environmen](https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/setting-up-your-local-dev-environment.md)
O arquivo original parece que já tem coisas novas, não sei como estamos fazendo isso.

Fix translation: setting-up-your-local-dev-environment.md

---

docs/docs/routing.md

[routing.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/routing.md)
Não traduzi o termo `prefetch/prefetching`. Na [planilha](https://docs.google.com/spreadsheets/d/1TLztI-jrPslCt0fgk4B9tGnhhS_7JQZJfMql1ePsIZo/edit#gid=0) não existe sugestão, dei uma pesquisada rápida e vi que o [Facebook também não traduziu](https://www.facebook.com/business/help/1514372351922333).
Acredito fazer parte da lista de termos bem disseminados.

Fix translation: routing.md

---

docs/contributing/docs-contributions.md

/docs/contributing/docs-contributions.md

Fix translation: docs-contributions.md

---

docs/docs/themes/using-a-gatsby-theme.md

[themes/using-a-gatsby-theme.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/themes/using-a-gatsby-theme.md)
Fiquei na dúvida em como traduzir "Gatsby theme shadowing"

Fix translation: themes/using-a-gatsby-theme

---

docs/docs/glossary/webpack.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/glossary/webpack.md

New translation: /glossary/webpack.md

---

docs/docs/different-organization-types.md

Traduzido o arquivo `different-organization-types`.
[Link do arquivo no repositório principal](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/different-organization-types.md)
Note que traduzi com certa liberdade, preferindo manter a clareza e significado da frase ao custo da tradução literal palavra por palavra.

New translation: different-organization-types.md

---

docs/docs/glossary/graphql.md

[/docs/glossary/graphql.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/glossary/graphql.md)
Nops

New translation: /docs/glossary/graphql.md

---

docs/docs/layout-components.md

[link para o layout-components](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/layout-components.md)

New translation: layout-components.md

---

docs/docs/css-libraries-and-frameworks.md

`/docs/docs/css-libraries-and-frameworks.md`
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/css-libraries-and-frameworks.md

New translation: css-libraries-and-frameworks.md

---

docs/docs/recipes/working-with-starters.md

[/docs/recipes/working-with-starters.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/working-with-starters.md)
Nops

New translation: /docs/recipes/working-with-starters.md

---

docs/docs/creating-prefixed-404-pages-for-different-languages.md

creating-prefixed-404-pages-for-different-languages.md
Estou na dúvida entre "página 404 localizada" ou "página 404 traduzida"?

New Translation: creating-prefixed-404-pages-for-different-languages.md

---

docs/docs/recipes/deploying-your-site.md

[/recipes/deploying-your-site.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/deploying-your-site.md)
Nas linhas 82 e 83, esse arquivo faz referência a dois outros que não existem nem aqui, e nem no repositório oficial.
Esses dois arquivos são `/docs/hosting-on-netlify` e `/packages/gatsby-plugin-netlify`

New translation: /recipes/deploying-your-site.md

---

docs/docs/adding-search-with-js-search.md

Adding search with js-search.md
Fiquei apenas em duvida se deveria traduzir a palavra “sanitizer” e “lifecycle method” ai deixei em ingles mesmo.

New translation: adding-search-with-js-search.md

---

docs/docs/audit-with-lighthouse.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/audit-with-lighthouse.md
A documentação em inglês do Lighthouse se difere da sua versão em português em relação as etapas necessárias para gerar um relatório da página. Desse modo, estou em crer que a versão em inglês é mais recente e logo deve ser utilizada em referências e hipertextos.

New translation: /docs/audit-with-lighthouse.md

---

docs/docs/mdx/plugins.md

[`docs/mdx/plugins.md`](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/mdx/plugins.md)

New translation: /mdx/plugins.md

---

docs/docs/deploying-to-aws-amplify.md

https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/deploying-to-aws-amplify.md
- Nas linhas 13 e 19 eu fiquei na dúvida se poderia colocar login mesmo no local de Sign in. Não encontrei uma palavra adequada além de "entrar" e ai optei por login.
- Na linha 25 que tinha dropdown eu também fiquei na dúvida se eu deixava dropdown ou botava menu suspenso. Acredito que dropdown seja um termo comum as pessoas  da nossa área. No final coloquei menu suspenso.

New Translation: deploying-to-aws-amplify.md

---

docs/docs/preparing-for-site-launch.md

[preparing-for-site-launch.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/preparing-for-site-launch.md)

New translation: preparing-for-site-launch.md

---

docs/docs/glossary/graphql.md
docs/docs/mdx/markdown-syntax.md

[/docs/mdx/markdown-syntax.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/mdx/markdown-syntax.md)
Fiquei em dúvida em como explicar *inline code*, seria _código em linha_ mesmo?

New translation: /docs/mdx/markdown-syntax.md

---

docs/docs/gatsby-image.md

New translation: gatsby-image.md

---

docs/docs/babel-plugin-macros.md

Foi traduzido o arquivo [`babel-plugin-macros.md`](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/babel-plugin-macros.md)
Não encontrei uma tradução adequada para a expressão "template literal tag", utilizei "identificador template literal" julgando que template literal faz parte do vocabulário de sintaxe do JavaScript. Se tiverem uma sugestão melhor, peço que me avisem por favor.

New translation: /docs/babel-plugin-macros.md
