gatsbyjs/gatsby-pt-BR

- docs/contributing/triaging-github-issues.md
Esta PR adiciona a tradução em pt-br do documento `triaging-github-issues.md`.
[triaging-github-issues.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/contributing/triaging-github-issues.md)
- Para o contexto do documento _maintenance_ foi traduzido para _suporte_, pois achei que _manutenção_ ficaria estranho.
- O título original _Labeling_ foi traduzido para _Etiquetas_, existem outras opções como: _rotulagem_ ou _etiquetagem_ :yum:
> Add triaging-github-issues translation to pt-br

- docs/docs/styling.md
[/docs/docs/styling.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/styling.md)
> Translate styling.md to pt-br

- docs/docs/path-prefix.md
[path-prefix.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/path-prefix.md)
Sugestões:
1. Chamar `path` de `rota` e não de `caminho`. No contexto de web development chamamos de rotas as URLs que o usuário interage na sua aplicação. Por exemplo, rota de usuário (`/user`), rota do blog (`/blog`).
2. `assets` a tradução para pt-BR seria "ativo", mas não faz sentido no contexto de web, acho que comunidade já está acostumada a referenciar como `assets`.
3. `helper` apesar de já ser uma palavra popular pode ser chamado de `função auxiliar`.
> translate: path-prefix.md

- docs/docs/creating-plugins.md
[creating-plugins.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/creating-plugins.md)
> Tradução para creating-plugins.md

- docs/docs/gatsby-on-linux.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/gatsby-on-linux.md
Se deve haver uma tradução para expressão TODO e da palavra Subsystem em Windows Subsystem Linux
> translate: gatsby-on-linux.md

- docs/docs/browser-support.md
> translate: browser-support.md

- docs/docs/testing-react-components.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/testing-react-components.md
> translate: testing-react-components.md

- docs/docs/tailwind-css.md
tailwind-css.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/tailwind-css.md
Algumas palavras como **utility-first** e **preflight** eu não traduzi porque senão não iam se encaixar no contexto, mas deixei elas como um link para suas respectivas documentação explicando as mesmas no site da documentação oficial do Tailwind. Qualquer erro, dúvida, ou sugestão, eu estou a inteira disposição.
> translate tailwind-css.md

- docs/docs/creating-slugs-for-pages.md
[docs/docs/creating-slugs-for-pages.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/creating-slugs-for-pages.md)
> Translate creating-slugs-for-pages.md

- docs/docs/customization.md
<a href="https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/customization.md">customization.md</a>
não
> traducao-customization.md

- docs/docs/preparing-for-deployment.md
docs/preparing-for-deployment.md
> translate: docs/preparing-for-deployment.md

- docs/docs/build-caching.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/build-caching.md
Em relação a palavra `build`, tive dúvidas em relação a tradução correta dependendo do contexto inserido.
> translate: build-caching.md

- docs/docs/emotion.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/emotion.md
> translate: emotion.md

- docs/docs/graphql.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/graphql.md
I translated to portuguese, but also kept the original words 'queries' e 'schema'. This way the person reading this document will be able to find and understand other documents more easily.
> translate: graphql.md 

- docs/docs/gatsby-repl.md
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-repl.md
Duas ressalvas:
- Fiquei em dúvida sobre mudar o título ou não, acabei deixando o original.
- Sempre que eu traduzo sou inclinado a não traduzir a palavra "output", como está no glossário para não traduzir "input" acabei deixando [output] sem traduzir também (apesar do contexto provavelmente ser diferente pras duas).
Tentei deixar o mais consistente possível com as traduções anteriores mas sempre tem a chance de algo escapar. x)
> docs: Translate gatsby-repl to pt-BR

- docs/docs/page-creation.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/page-creation.md
> Translating page-creation

- docs/docs/importing-media-content.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/importing-media-content.md
> translate: importing-media-content.md

- docs/docs/creating-a-sitemap.md
[creating-a-sitemap.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/creating-a-sitemap.md)
Dúvida quanto a `build` se deixa build mesmo ou se coloca algo como `compilação/construção`(?)
> Translates creating-a-sitemap.md

- docs/docs/query-extraction.md
[query-extraction.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/query-extraction.md)
> Tradução query-extraction.md

- docs/docs/add-seo-component.md
[Site](https://www.gatsbyjs.org/docs/add-seo-component/)
[Repositório](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/add-seo-component.md)
Fiquei com um pouco de dificuldade de traduzir a palavra `alias` na documentação, quando precisamos renomear os dados da consulta. Se alguém tiver uma outra sugestão para essa parte eu agradeço:
> The next step is to destructure the data from the query and to create an object that checks if the props were used — if not the default values are utilized. The name aliasing comes in handy here: It avoids name collisions.
Como pensei em traduzir: 
> A próxima etapa é desestruturar os dados da consulta e criar um objeto que verifique se os objetos foram usados - se não forem utilizados os valores padrão. Renomear os itens da consulta é útil aqui: …
> docs: Translate add-seo-component.md

- docs/docs/using-fragments.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/using-fragments.md
Não traduzi a parte do código, pois achei que ficaria muito estranho.
> Tradução completa do arquivo using-fragments.md

- docs/docs/api-files-gatsby-config.md
`docs/docs/api-files-gatsby-config.md`
> traducao api-files-gatsby-config

- CODEOWNERS
While building https://isgatsbytranslatedyet.org ([source code](https://github.com/nutboltu/is-gatsby-translated-yet)), I found this repository has an incorrect code owner name which never exists.
It seems @Italox doesn't exist and @iaurg  is the actual code owner.
This PR is to change the code owner name from  @Italox to @iaurg
> docs: change codeowner name from italox to iaurg

- docs/docs/typography-js.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/typography-js.md
> translate: typography-js.md

- docs/docs/adding-search.md
[adding-search.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/adding-search.md)
Em alguns momentos fiquei em dúvida entre utilizar pesquisa ou busca na hora de traduzir _search_. Tentei alternar para evitar repetição.
> Translation of adding-search.md

- docs/docs/global-css.md
[global-css.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/global-css.md)
> Translate global-css.md

- docs/docs/answering-it-security.md
> Translate answering-it-security.md

- docs/docs/themes.md
[themes.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/themes.md)
> Add themes.md traduction

- docs/docs/using-a-plugin-in-your-site.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/using-a-plugin-in-your-site.md
> Traducao using-a-plugin-in-your-site

- docs/docs/loading-plugins-from-your-local-plugins-folder.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/loading-plugins-from-your-local-plugins-folder.md
> Tradução loading-plugins

- docs/docs/glossary/node.md
[node.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/glossary/node.md)
Traduzi `runtime` para interpretador, mas não tenho certeza se a tradução mais adequada.
> New translation: glossary/node.md

- docs/docs/deploying-to-gitlab-pages.md
`docs/docs/deploying-to-gitlab-pages`.
Palavras relacionadas a `build` não foram traduzidas por não haver um termo apropriado.
> New translation: deploying-to-gitlab-pages

- docs/docs/schema-sift.md
[schema-sift.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/schema-sift.md)
> New translation: schema-sift.md

- docs/docs/plugins.md
Arquivo plugins.md traduzido para o Português do Brasil.
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/plugins.md
https://github.com/JuanVieiraPrado/gatsby-pt-BR/blob/master/docs/docs/plugins.md
> Fix translation: plugins.md

- docs/accessibility-statement.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/accessibility-statement.md
> New translation: accessibility-statement.md

- docs/docs/local-https.md
[local-https.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/local-https.md)
Esta é minha primeira contribuição, mas pretendo poder ajudar muito mais futuramente.
> New translation: local-https.md

- docs/docs/glossary/react.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/glossary/react.md
> New translation:  /glossary/react.md

- docs/docs/theme-ui.md
[/docs/theme-ui.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/theme-ui.md)
Não traduzi o termo **shadowing**, **component shadowing** e **shadowed**, penso ser um termo disseminado na comunidade. Tentei encaixar a tradução para uma maneira que deixe clara a ideia dessa técnica, além de manter essas palavras em _itálico_ para indicar que se tratam de palavras estrangeiras.
> New translation: /docs/theme-ui.md

- docs/docs/deploying-to-s3-cloudfront.md
[Link para o arquivo deploying-to-s3-cloudfront.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/deploying-to-s3-cloudfront.md)
> New translation: deploying-to-s3-cloudfront.md

- docs/docs/gatsby-link.md
- docs/docs/local-https.md
[/docs/docs/gatsby-link.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-link.md)
> New translation: /docs/docs/gatsby-link.md

- docs/docs/sourcing-from-graphcms.md
[/docs/sourcing-from-graphcms.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/sourcing-from-graphcms.md)
> New translation: /docs/sourcing-from-graphcms.md

- docs/docs/remark-plugin-tutorial.md
https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/remark-plugin-tutorial.md
Há certa ambiguidade na tradução do título 'Remark Plugin Tutorial' → 'Tutorial do Plugin Remark', já que o tutorial não refere-se ao plugin Remark em si, e sim à produção de sub-plugins para o mesmo. Traduzi para 'Tutorial de Plugins para o Remark'. Sintam-se livres para sugerir mudanças.
É citada com frequência a **Markdown Abstract Syntax Tree**. Optei por traduzir o termo para **Árvore de Sintaxe Abstrata do Markdown** e mencioná-lo nos parágrafos seguintes por sua sigla em inglês (AST), obedecendo o fluxo do documento original. Sintam-se livres para sugerir mudanças.
Em todas as ocorrências no documento o termo **node** foi traduzido para o termo **nó**, como sugerido por outro registro do …
> New translation: remark-plugin-tutorial.md

- docs/docs/progressive-web-app.md
Tradução 
docs\docs\progressive-web-app.md
> New translation: progressive-web-app.md

- docs/docs/recipes/pages-layouts.md
[recipes/pages-layouts.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/recipes/pages-layouts.md)
> New translation: /recipes/pages-layouts.md
